version: '3'

services:
  front-end:
    image: nginx:latest
    container_name: alpha-front-end
    ports:
        - "80:80"
    volumes:
        - .:/usr/share/nginx/html
        - ./backend:/exclude

  back-end:
    build: ./backend
    container_name: alpha-back-end
    ports:
      - "3000:3000"

